In [1]:
import matplotlib as plt
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("./data/Linguistic_features.csv")

In [4]:
df.describe()

,# Areas before prompt (0-5 from identified areas),Total words,# hesitations,# social,# prompts,Complexity,Task Performance,# fruits/animals before prompt,# fruits/animals total,# unique fruits/animal total,# repeated,# hesitations.1,# social.1,# prompts,Task Performance.1
count,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,0.0,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,0.0
mean,3.414286,303.628571,10.542857,1.171429,4.214286,0.631714,NaN,14.342857,31.200000,21.800000,4.071429,12.114286,4.957143,5.371429,NaN
std,0.985296,92.923714,7.314242,1.035198,1.751958,0.091556,NaN,8.008846,13.740451,8.901392,2.080422,7.461093,3.052372,1.331572,NaN
min,1.000000,79.000000,1.000000,0.000000,1.000000,0.420000,NaN,2.000000,6.000000,3.000000,1.000000,5.000000,0.000000,1.000000,NaN
25%,3.000000,232.500000,4.250000,0.000000,3.000000,0.562500,NaN,9.000000,22.000000,17.000000,3.000000,8.000000,3.000000,5.000000,NaN
50%,3.000000,289.000000,9.500000,1.000000,4.000000,0.640000,NaN,13.000000,30.000000,21.500000,4.000000,11.000000,5.000000,5.000000,NaN
75%,4.000000,357.500000,15.000000,2.000000,5.000000,0.700000,NaN,18.000000,40.750000,28.750000,5.000000,15.000000,7.000000,6.000000,NaN
max,5.000000,600.000000,31.000000,5.000000,10.000000,0.790000,NaN,44.000000,73.000000,44.000000,11.000000,59.000000,14.000000,9.000000,NaN

In [ ]:
df_cookie = df[(df[])]